//
//  CountriesListInteractor.swift
//  CountriesApp
//
//  Created by Cesar Armando on 11/11/19.
//  Copyright (c) 2019 Cesar Armando. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CountriesListBusinessLogic
{
  func getCountries()
}

protocol CountriesListDataStore
{
  //var name: String { get set }
}

class CountriesListInteractor: CountriesListBusinessLogic, CountriesListDataStore
{
  var presenter: CountriesListPresentationLogic?
  var worker: CountriesListWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func getCountries()
  {
    worker = CountriesListWorker()
    worker?.getCountries { (countries) in
        print(countries?.count)
    }
    
    let response = CountriesList.LoadDetail.Response()
    presenter?.presentCountries(response: response)
  }
}
