//
//  CountriesListViewController.swift
//  CountriesApp
//
//  Created by Cesar Armando on 11/11/19.
//  Copyright (c) 2019 Cesar Armando. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CountriesListDisplayLogic: class
{
    func displaySomething(viewModel: CountriesList.LoadDetail.ViewModel)
}

class CountriesListViewController: UIViewController, CountriesListDisplayLogic
{
    var interactor: CountriesListBusinessLogic?
    var router: (NSObjectProtocol & CountriesListRoutingLogic & CountriesListDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = CountriesListInteractor()
        let presenter = CountriesListPresenter()
        let router = CountriesListRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        self.title = "Countries"
        loadCountries()
    }
    
    
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func loadCountries()
    {
        interactor?.getCountries()
    }
    
    func displaySomething(viewModel: CountriesList.LoadDetail.ViewModel)
    {
        //nameTextField.text = viewModel.name
    }
}
