//
//  CountriesListRouter.swift
//  CountriesApp
//
//  Created by Cesar Armando on 11/11/19.
//  Copyright (c) 2019 Cesar Armando. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CountriesListRoutingLogic
{
    func showCountryDetails(viewController: UIViewController, country: Country)
}

protocol CountriesListDataPassing
{
    var dataStore: CountriesListDataStore? { get }
}

class CountriesListRouter: NSObject, CountriesListRoutingLogic, CountriesListDataPassing
{
    weak var viewController: CountriesListViewController?
    var dataStore: CountriesListDataStore?
    
    func showCountryDetails(viewController: UIViewController, country: Country) {
        let viewVC = CountryDetailViewController()
        var destinationDS = viewVC.router!.dataStore!
        passDataToCountryDetails(source: country, destination: &destinationDS)
        viewController.navigationController?.pushViewController(viewVC, animated: true)
    }
    
    func passDataToCountryDetails(source: Country, destination: inout CountryDetailDataStore) {
        destination.country = source
    }
}
