//
//  CountryDetailInteractor.swift
//  CountriesApp
//
//  Created by Cesar Armando on 11/11/19.
//  Copyright (c) 2019 Cesar Armando. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CountryDetailBusinessLogic {
    func presentCountry()
}

protocol CountryDetailDataStore {
    var country: Country? { get set }
}

class CountryDetailInteractor: CountryDetailBusinessLogic, CountryDetailDataStore {
    var presenter: CountryDetailPresentationLogic?
    var worker: CountryDetailWorker?
    var country: Country?
    
    // MARK: Do something
    
    func presentCountry() {
        if let country = country {
            presenter?.presentCountry(country: country)
        }
    }
}
