//
//  CountryDetailPresenter.swift
//  CountriesApp
//
//  Created by Cesar Armando on 11/11/19.
//  Copyright (c) 2019 Cesar Armando. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CountryDetailPresentationLogic {
    func presentCountry(country: Country)
}

class CountryDetailPresenter: CountryDetailPresentationLogic {
    weak var viewController: CountryDetailDisplayLogic?
    
    // MARK: Do something
    func presentCountry(country: Country) {
        viewController?.country = country
    }
}
