//
//  CountriesListWorker.swift
//  CountriesApp
//
//  Created by Cesar Armando on 11/11/19.
//  Copyright (c) 2019 Cesar Armando. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

class CountriesListWorker{
    func getCountries(completion: @escaping(_ countries: [Country]? ) -> Void) {
        let url = ServicesManager.shared.urlForEndpoint(endpoint: .getAllCountries)
        genericRequest(urlString: url, method: HTTPMethod.get, headers: [:]) { (error, response: [Country]?, _) in
            completion(response)
        }
    }
}
